apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacexample-8ztb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacexample-8ztb
    app.kubernetes.io/part-of: hactest1
  name: hacexample-8ztb
  namespace: utherp0-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: hacexample-8ztb
status:
  loadBalancer: {}
